### ISSUE TITLE
AttributeError: __enter__ with redis 2.10.5

### ISSUE THREAD

**Issue by Basit-qc** [codingjoe/django-health-check#231]
Started happening with redis 2.10.5. Was working fine with redis 3.3.5.

Response:
```
{
    "CacheBackend": "working",
    "CeleryHealthCheckCelery": "working",
    "DatabaseBackend": "working",
    "DefaultFileStorageHealthCheck": "working",
    "RedisHealthCheck": "unavailable: Unknown error"
}
```
Logs:
```
ERROR - unavailable: Unknown error (backends.py,49)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/health_check/contrib/redis/backends.py", line 24, in check_status
    with from_url(self.redis_url) as conn:
AttributeError: __enter__
```

**Comment by codingjoe** [comment]
Hi @Basit-qc 
Thanks for reaching out. As I understand your comment, you actually downgraded the redis package, right? Might I ask why you did that?

So we don't test against older version of Redis and don't have "official" support for it. That being said, I would really like to understand why you downgraded. There might be a very good reason, and we should add backwards compatibility for older redis version.

I will close the issue for now and maybe reopen it if we need to make changes.

Best
-Joe

**Comment by Basit-qc** [comment]
Thanks @codingjoe for looking into the reported issue.
I was getting error on registering celery task with upgraded redis
```
AttributeError: 'float' object has no attribute 'items' 
```
Searched for solutions and it was suggested to downgrade redis version.
e.g. 
https://github.com/andymccurdy/redis-py/issues/1068
http://www.programmersought.com/article/2653334850/
https://github.com/celery/celery/issues/5175
That's why I had to downgrade and now my celery part is working fine.

**Comment by codingjoe** [comment]
@Basit-qc I have stumbled on the issue myself, but is fixed been fixed in kombu>=4.2.2. So instead of downgrading Redis driver, I would recommend upgrading kombu. Please understand that the Redis health check is a new feature. I am sure you understand, that we can't provide support for old versions of all dependencies one might use.

**Comment by Basit-qc** [comment]
Got it. :+1: 
Thank you @codingjoe for suggesting the solution. 
I will try updating kombu, it is currently 4.2.1.

**Comment by codingjoe** [comment]
Let me know how it goes. And sorry for my language, I just read my comment again and it looks like had a stroke mid sentence. Glad that you could make sense out of it 😅

**Comment by Basit-qc** [comment]
It worked :+1: . Upgraded kombu to `4.5.0` and now RedisHealthCheck is back up with working Celery. Thank you @codingjoe for all the help :)
