### ISSUE TITLE
It doesn't work with Django 4.1

### ISSUE THREAD

**Issue by aleixmorgadas** [codingjoe/django-health-check#373]
Error:

```
# -*- coding: utf-8 -*-
    """
    URLs.
    """
>   from django.conf.urls import include, url
E   ImportError: cannot import name 'url' from 'django.conf.urls' (.../.venv/lib/python3.11/site-packages/django/conf/urls/__init__.py)

../../../.venv/lib/python3.11/site-packages/health_check/urls.py:5: ImportError
```

I saw the deprecation notice here. https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-4-0

**Comment by lociii** [comment]
What release are you using?  
This package uses `path` from `django.urls`, see https://github.com/revsys/django-health-check/blob/3.17.0/health_check/urls.py

**Comment by aleixmorgadas** [comment]
We are using 3.17.0 :confused: 

I will take a closer look

**Comment by lociii** [comment]
@aleixmorgadas can this be closed?

**Comment by aleixmorgadas** [comment]
Sure

**Comment by lociii** [comment]
Would you mind?
