### ISSUE TITLE
Bug: check_status() fails after upgrading to 3.18

### ISSUE THREAD

**Issue by julius-prvz** [codingjoe/django-health-check#413]
Hi all,

I just want to make you aware of an issue I've encountered after upgrading from 3.17 to 3.18:

`CustomCheck.check_status() got an unexpected keyword argument 'subset'`

This error has been raised for some of our custom health checks. I suppose it's related to this PR? https://github.com/revsys/django-health-check/pull/390

From my perspective, the new feature doesn't work with the example provided in the Readme.

**Comment by frankwiles** [comment]
Thanks for reporting this, I'm looking into it now!
